### ISSUE TITLE
Add option to disable warnings .svelte editors

### ISSUE THREAD

**Issue by chriscalo** [sveltejs/svelte-atom#6] opened 2019-10-07 15:26 UTC
The warnings are a distraction because things work fine without addressing them.

**Comment by rixo** [comment] 2022-02-15 12:37
I believe you're mentioning erroneous warnings that were caused by lacking compatibility of this plugin with Svelte 3.

In the new version (1.0.0) of this plugin, any error/warning that you see should be an actual problem.

If really you want to disable even non-erroneous warnings, this would be done in the linter package. (Unfortunately, at the time of writing, disabling the kind of linters provided by this plugin is [not supported in the `linter`](https://github.com/steelbrain/linter/issues/1603), which is what I personally use -- don't know if this applies to your situation).

I'm closing this because the formulation "because things work fine without addressing them" makes me think that the actual request was about erroneous warnings, which should be fixed now.

If someone is really interested in a "disable diagnostics" feature, this might be doable. Please open a new issue and we'll consider it.

**Comment by rixo** [comment] 2022-02-16 16:05
Well... Turns out we are now linting JS Component with TS, resulting in type warnings & errors that do fall in the "erroneous linting" category.

I guess an option to disable TS diagnostics is needed indeed. I suppose it should be enabled by default for TS, and disabled for JS.

**Comment by rixo** [comment] 2022-02-17 00:13
Should be fixed in v1.1.0, that adds options to disable diagnostics for ts, js, or svelte.

**Closed as completed by rixo** 2022-02-17 00:13 UTC
